# version: "3.9"
# services:
#   c-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/usr/src/app
#     working_dir: /usr/src/app
#     stdin_open: true
#     tty: true


version: "3.9"
services:
  c-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app  # Sync local files with the container
    working_dir: /usr/src/app
    stdin_open: true
    tty: true